language: java
notifications:
  slack:
    secure: ArWucVG3wQs7+zyrrbJjksjfxIZ4/C5xCpVg9CCTjy2CVg1ZxPfFm1RAutpvnMfhynguV4qojtfzXgNKdJTYeuLHmm69YWouSIzS3nBmec1ycc8CqbG7GwTvuwddyu839x0NFVccxmjUVZCdNw3V7ErroEpzExGg6EETtGl4stDRx1wyPkLJ8akx6ohhomIOraXrCDzXtcfCf2DKGIPfZqjQInBayJpvPLZKnJc7LEUYiSP5gExrqjKTEDjqCvllLb9mr3oBpHpdq6kVK/Rs4IXhI2m/ZPZXC02CjDN8qOywh8M58IuVoASexrGhswtOGhVYfTogJtXT4aOqYSRtycLzZIkC09C1WMZ2a3sWRk8ZYjUZJPTyfFLE49Z9qKOdjL7Di9PfUnu72XyL4FQf/SK9D/KZlkI7k8h9OJR/IYjFBfeMAHXKi0wu1HvxYVamWzLlRcE9xh2NSUFBGC8XpfVnLKMnmA2KRZfzNgkqSfqU9YvIQ6y8vOo6guq1bP9qCNqWx/2Lq5p4qNzggI3syMkoDkpjkOz0+E0t9CI4Y98RsTEWwJvnNCu4sa883JXeESuJKaSEOnyRxGYCTVVjT55UWmuW79Z5aXmv3udLm8JqHkjOVvlgP7scWORe2h/N2/ArWH9Jr+nZP0V2feZ5R9w1CICW76SMpz3Q+KVDMBA=

addons:
  sonarcloud:
    organization: davidwpowell-github
    token:
      secure: HnPMSuDRi9Tw/27+AfHacmBef7SseJ6RK3ktA+bQHnqJ1A6CL9684YHK3kH9FxQVLB2ydi6MyKgSZIWLVjfOLn3CpoYt3y/cwXp9IHqk5TZoIb6monrcRrRkFLSsb8NE8fLyg5WFTVfSx/ogSr4yncfh0wT/4wB5A05UrRpuRPti5NBs/CorT3yZVjlhODyIN7C0Dj5wWt/jnfvQmTW4tKtTAtXMW6J2ZoBgeYDRRgQYa6BmlMDqUcOvzorhU39nUpzBAWtMWNEKSD3BzrN65cIK2bD1gZpYezCF9FOJ8mBHraXxHI55OS8iTfwNjjXZLgdtd7NsIXQUimUo7w0MwJfrPa3wdVPFAYJKd8ZUM9aC/fS/b97Qas8DKFu1F74da/RUcuLIW054pS6F39LFBOXErNWs6nmXCBBv4TAa1xByrccouxFdZ3agpZk2IJorNFvM7fRz42AZXb3xLrSdQdd9fqjvJlGpu4xKq6M8LX7tNRS1IzZGJKwcawjy+1ESFVMLjDpIMHiYqRX86q54xthp886Ce2tQsgNkCfBa4jSSlQuLvXxIIZPrQAjGWEdA7YCuXls2KFHNIuVQruCPvKqnPU3Ib3ek0mKNDcHv3ba6vSW8sBQl5K5ljeoN4rCK1WcZcgGFIkgDu35IaPX24knidI3SDT/1XPKX4F6sjkY=
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

deploy:
  provider: heroku
  api_key:
    secure: nwyWMc7XB9RTKQ8a0LWNY2EMfiWsTOIXpuh0bBHax3jM59gjx4tPvdPsKBno/br+GZzKjOalw4fb5oxNBtUrc8VWK3DnOEnLYJjfkavwoXGI9nU8IkiNb2ZFzSAbAdO4vdk1h2QC1RCU2hb8KXDb5hf+BJdXx5qbtgPKyFsO/MRmBydhKkLqtS3F5Pbe2fJFAT88NQvnhrLaPxiq9m/vV/Rwradw4qG6/v/Tovl0XTCtubHXZJ18g/SZ2diXrkmVwWfuksDnrL/2e8CBc0oWs8l7vpJ1twm7iMxpwVkpXEoeEuK/5Atd7k52jHRVVxC5z/Fmo7NKg7qr3AuOJI4dSD6QSHaZGjfCvBKkRIHIPtfzgl/f7gAwgDq1aHRmM0/w0hss58+i3EOxvBS4rD7UaUiG0xNuSOgkYKFiG7e+3NKQtRvhZEGQOWNIy4XXZSWwn1K+t43TGT09bJ1n7xH1mrCAT5yaevmFKTlG2CYQn0LyQY1koheBYQavqvh108fs5tdT9fzUaHrSYUusVk0SnP9LrgUVcCZUh0LZdNp5v7TselINc76sXTXL9yz9SZHLZS5E4bw3lEhKZbHQBcVDb2yhzxfPWDtD6qkheV2GhkbVxrGS9UfiHavd92GPoAOtIBYTqo0A2Gmsd7dBwl5uN8TsJWyb3up/OT6h8FBRP7A=
  app: shielded-river-77060
  on:
    repo: davidwpowell/rest-client
